#!/bin/bash
# manually kill the iguana you need to restart first!

# unlock any locked utxos. This will unlock utxos for both iguans, need a filter for address to only unlock the pubkey you need to restart. 
komodo-cli lockunspent true `komodo-cli listlockunspent | jq -c .` 

# Start normally, no split is default on this branch. 
stdbuf -oL $1 ../agents/iguana notary & #> iguana.log 2> error.log  &

myip=`curl -s4 checkip.amazonaws.com`
source pubkey.txt

sleep 4
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"$myip\"}"
sleep 3

# Season 6 peer IPs
SeedIPs=("209.222.101.247" "103.195.100.32" "77.75.121.138" "77.75.121.140" "77.74.197.115" "158.69.18.121" "167.114.197.249" "15.235.64.45" "177.54.149.80" "82.202.230.251" "177.54.144.116" "38.91.101.236" "49.12.83.114" "162.55.89.237" "2.56.154.200");
for IP in "${SeedIPs[@]}";
	do
		curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"${IP}\"}";
	done



# add coins
./add_coins

sleep 10

# dpow for KMD->LTC.
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"KMD\",\"pubkey\":\"$pubkey\"}"

sleep 10

# dpow for ACs
./dpowassets
