#!/bin/bash
# manually kill the iguana you need to restart first!

# unlock any locked utxos. This will unlock utxos for both iguans, need a filter for address to only unlock the pubkey you need to restart. 
komodo-cli lockunspent true `komodo-cli listlockunspent | jq -c .` 

# Start normally, no split is default on this branch. 
stdbuf -oL $1 ../agents/iguana notary & #> iguana.log 2> error.log  &

myip=`curl -s4 checkip.amazonaws.com`
source pubkey.txt

sleep 4
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"$myip\"}"
sleep 3

+# Season 8 Main peers
# 15.235.204.174 Dragonhound_AR
# 209.222.101.247 Dragonhound_NA
# 178.159.2.9 Dragonhound_EU
# 51.161.198.87 Dragonhound_SH
# 103.195.100.32 Dragonhound_DEV
# 141.94.195.209 QA_DEV
# 148.113.1.52 gcharang_AR
# 51.161.209.100 gcharang_SH
# 51.161.172.84 gcharang_SH2
# 148.113.8.6 gcharang_DEV
# 178.159.2.6 blackice_eu
# 51.79.18.36 blackice_na

SeedIPs=("15.235.204.174" "209.222.101.247" "178.159.2.9" "51.161.198.87" "103.195.100.32" "141.94.195.209" "148.113.1.52" "51.161.209.100" "51.161.172.84" "148.113.8.6" "178.159.2.6" "51.79.18.36");
for IP in "${SeedIPs[@]}";
do
	curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"${IP}\"}";
done

# add coins
./add_coins

sleep 10

# dpow for KMD->LTC.
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"KMD\",\"pubkey\":\"$pubkey\"}"

sleep 10

# dpow for ACs
./dpowassets
