#!/bin/bash
# manually kill the iguana you need to restart first!

# unlock any locked utxos. This will unlock utxos for both iguans, need a filter for address to only unlock the pubkey you need to restart. 
komodo-cli lockunspent true `komodo-cli listlockunspent | jq -c .` 

# Start normally, no split is default on this branch. 
stdbuf -oL $1 ../agents/iguana notary & #> iguana.log 2> error.log  &

myip=`curl -s4 checkip.amazonaws.com`
source pubkey.txt

sleep 4
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"${myip}\"}"
sleep 3

# Season 7 Main peers
# Dragonhound_AR 15.235.204.174
# Dragonhound_NA 209.222.101.247
# Dragonhound_DEV 103.195.100.32
# gcharang_AR 148.113.1.52
# gcharang_SH 51.161.209.100
# gcharang_DEV 148.113.8.6
# Alright_DEV 144.76.80.75
# Alright_EU 65.21.77.109
# Marmara1 89.19.26.211
# Marmara2 89.19.26.212

SeedIPs=("15.235.204.174" "209.222.101.247" "103.195.100.32" "148.113.1.52" "51.161.209.100" "148.113.8.6" "144.76.80.75" "65.21.77.109" "89.19.26.211" "89.19.26.212");
for IP in "${SeedIPs[@]}";
do
	curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"${IP}\"}";
done

# add coins
./add_coins

sleep 30

# dpow for KMD->LTC.
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"KMD\",\"pubkey\":\"${pubkey}\"}"

sleep 20

# dpow for ACs
./dpowassets
