name: CI

on: [push, pull_request]
jobs:
  build:
    name: Build dPoW client "iguana" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install libsodium-dev libncurses-dev zlib1g-dev libprotobuf-dev protobuf-compiler libgtest-dev libdb++-dev libevent-dev libcurl4-gnutls-dev -y
    - name: Install nanomsg
      run: |
        git clone https://github.com/nanomsg/nanomsg
        cd nanomsg
        cmake . -DNN_TESTS=OFF -DNN_ENABLE_DOC=OFF
        make -j2
        sudo make install
        sudo ldconfig
    - name: Build dpow client "iguana"
      run: cd iguana && make -j3
